### ISSUE TITLE
Application not publicly hosted

### ISSUE THREAD

**Issue by Hmittal15** [BigDataIA-Spring2023-Team-11/Assignment2#26]
Expected Behavior: We should be able to access the application from a public URL
Current Behavior: No public URL available
Possible Solution: Publish the docker image on public instance
Steps to Reproduce: Try to navigate to "Streamlit link : http://44.212.9.212:8091/" provided in repository readme.md file
Possible Implementation: Publish the docker image on public instance
<img width="1116" alt="Screenshot 2023-03-03 001026" src="https://user-images.githubusercontent.com/108916132/222636755-07b38249-ec4f-43b3-b6c1-1041e230d190.png">

**Comment by abhatt13** [comment]
The instance was shutdown due to a resource crunch. We could have restarted our EC2 instance for user testing if the request had been made before the deadline. Please let us know a suitable timeframe when you need the instance up and running.
